apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akscluster-5d74"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akscluster-5d74"
  template:
    metadata:
      labels:
        app: "akscluster-5d74"
    spec:
      containers:
        - name: "akscluster-5d74"
          image: "acrmilaha.azurecr.io/akscluster"
          ports:
          - containerPort: 80